root: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 6
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  "@typescript-eslint/semi": warn
  curly: warn
  eqeqeq: warn
  no-throw-literal: warn
  semi: 0
  no-unused-vars: 0
